Use mysql root user instead of monitoring
SUSE-Cloud/supportutils-plugin-suse-openstack-cloud pull request #101
Opened 2020-01-27 17:10 UTC by djoreilly

The monitoring user exists only on crowbar installations, so
a couple of mysql commands fail on ardana installations. The
default root user works with crowbar and ardana.

2020-01-27 17:36 UTC, nicolasbock approved these changes
LGTM

2020-01-27 17:37 UTC, nicolasbock requested changes
Actually, could you cherry pick this change once master is merged?

2020-01-27 17:39 UTC, djoreilly commented
@nicolasbock sure

2021-01-14 08:50 UTC, JanZerebecki approved these changes

2021-01-14 08:51 UTC, JanZerebecki commented
Backport of https://github.com/SUSE-Cloud/supportutils-plugin-suse-openstack-cloud/pull/100

2021-01-18 13:49 UTC, gosipyan approved these changes

2021-01-18 13:54 UTC, merged